// Mocks generated by Mockito 5.4.5 from annotations
// in cresce_challenge_mobile/test/mocks/mock_stores.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:cresce_challenge_mobile/lib/app/modules/discount/stores/discount_store.dart'
    as _i7;
import 'package:cresce_challenge_mobile/lib/app/modules/discount/stores/product_store.dart'
    as _i4;
import 'package:cresce_challenge_mobile/lib/shared/models/discount_model.dart'
    as _i8;
import 'package:cresce_challenge_mobile/lib/shared/models/product_model.dart'
    as _i5;
import 'package:cresce_challenge_mobile/lib/shared/services/api_service.dart'
    as _i2;
import 'package:mobx/mobx.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiService_0 extends _i1.SmartFake implements _i2.ApiService {
  _FakeApiService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeObservableList_1<T> extends _i1.SmartFake
    implements _i3.ObservableList<T> {
  _FakeObservableList_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReactiveContext_2 extends _i1.SmartFake
    implements _i3.ReactiveContext {
  _FakeReactiveContext_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductStore extends _i1.Mock implements _i4.ProductStore {
  MockProductStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiService get apiService => (super.noSuchMethod(
        Invocation.getter(#apiService),
        returnValue: _FakeApiService_0(
          this,
          Invocation.getter(#apiService),
        ),
      ) as _i2.ApiService);

  @override
  _i3.ObservableList<_i5.ProductModel> get products => (super.noSuchMethod(
        Invocation.getter(#products),
        returnValue: _FakeObservableList_1<_i5.ProductModel>(
          this,
          Invocation.getter(#products),
        ),
      ) as _i3.ObservableList<_i5.ProductModel>);

  @override
  set products(_i3.ObservableList<_i5.ProductModel>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #products,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  set isLoading(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoading,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.ReactiveContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeReactiveContext_2(
          this,
          Invocation.getter(#context),
        ),
      ) as _i3.ReactiveContext);

  @override
  _i6.Future<void> loadProducts() => (super.noSuchMethod(
        Invocation.method(
          #loadProducts,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i5.ProductModel? getProductById(String? productId) =>
      (super.noSuchMethod(Invocation.method(
        #getProductById,
        [productId],
      )) as _i5.ProductModel?);
}

/// A class which mocks [DiscountStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiscountStore extends _i1.Mock implements _i7.DiscountStore {
  MockDiscountStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ObservableList<_i8.DiscountModel> get discounts => (super.noSuchMethod(
        Invocation.getter(#discounts),
        returnValue: _FakeObservableList_1<_i8.DiscountModel>(
          this,
          Invocation.getter(#discounts),
        ),
      ) as _i3.ObservableList<_i8.DiscountModel>);

  @override
  set discounts(_i3.ObservableList<_i8.DiscountModel>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #discounts,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.ReactiveContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeReactiveContext_2(
          this,
          Invocation.getter(#context),
        ),
      ) as _i3.ReactiveContext);

  @override
  _i6.Future<void> loadDiscounts() => (super.noSuchMethod(
        Invocation.method(
          #loadDiscounts,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void addDiscount(_i8.DiscountModel? discount) => super.noSuchMethod(
        Invocation.method(
          #addDiscount,
          [discount],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateDiscount(_i8.DiscountModel? updatedDiscount) => super.noSuchMethod(
        Invocation.method(
          #updateDiscount,
          [updatedDiscount],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateDiscountStatus(
    String? discountId,
    bool? newStatus,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateDiscountStatus,
          [
            discountId,
            newStatus,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
